services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pizza_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - pizza_net

  web:
    image: nginx:alpine
    container_name: pizza_web
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pizza_net

networks:
  pizza_net: